# Generated by Django 5.0.2 on 2024-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email_cliente', models.CharField(blank=True, max_length=25, null=True)),
                ('fecha_cotizacion', models.DateField(blank=True, null=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
                ('medio_pago', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'carrito_compras',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacturaProductosUsuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('unidades', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'factura_productos_usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_factura', models.IntegerField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('nombre_cliente', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=45, null=True)),
                ('email', models.CharField(blank=True, max_length=45, null=True)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('fecha_facturacion', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
                ('estado_factura', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('ruta', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cantidad_disponible', models.IntegerField(blank=True, null=True)),
                ('cantidad_ventas', models.IntegerField(blank=True, null=True)),
                ('carrito_compras_id', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('estado_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria_id', models.IntegerField(blank=True, max_length=45, null=True)),
                ('subcategoria_id', models.IntegerField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'subcategoria_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('telefono', models.IntegerField()),
                ('permisos', models.CharField(max_length=50)),
                ('estado_usuario', models.IntegerField()),
                ('rol', models.IntegerField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
        migrations.AlterModelOptions(
            name='empleados',
            options={'managed': False},
        ),
    ]
