# Generated by Django 5.0.2 on 2024-04-09 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carritocompras_categoria_facturaproductosusuarios_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empleados',
            table='empleados',
        ),
    ]
