# Generated by Django 5.0.2 on 2024-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=45, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('fecha_modificacion', models.CharField(blank=True, max_length=45, null=True)),
                ('estado_producto', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria_id', models.IntegerField(blank=True, max_length=45, null=True)),
                ('subcategoria_id', models.IntegerField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
    ]
